# Generated by Django 5.2.12 on 2026-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('standard', 'Стандартная зона'), ('vip', 'VIP зона'), ('gaming', 'Игровая зона')], max_length=25)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('price_per_hour', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers/')),
            ],
        ),
    ]
